// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: travel.proto

package homestayservice

import (
	"context"

	"go-zero-looklook/app/travel/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseResp                    = pb.BaseResp
	BusinessListReq             = pb.BusinessListReq
	BusinessListResp            = pb.BusinessListResp
	CommentListReq              = pb.CommentListReq
	CommentListResp             = pb.CommentListResp
	GoodBossReq                 = pb.GoodBossReq
	GoodBossResp                = pb.GoodBossResp
	GuessListReq                = pb.GuessListReq
	GuessListResp               = pb.GuessListResp
	Homestay                    = pb.Homestay
	HomestayBusiness            = pb.HomestayBusiness
	HomestayBusinessBoss        = pb.HomestayBusinessBoss
	HomestayBusinessListInfo    = pb.HomestayBusinessListInfo
	HomestayBussinessDetailReq  = pb.HomestayBussinessDetailReq
	HomestayBussinessDetailResp = pb.HomestayBussinessDetailResp
	HomestayBussinessListReq    = pb.HomestayBussinessListReq
	HomestayBussinessListResp   = pb.HomestayBussinessListResp
	HomestayComment             = pb.HomestayComment
	HomestayDetailReq           = pb.HomestayDetailReq
	HomestayDetailResp          = pb.HomestayDetailResp
	HomestayListReq             = pb.HomestayListReq
	HomestayListResp            = pb.HomestayListResp

	HomestayService interface {
		// 民宿服务
		HomestayList(ctx context.Context, in *HomestayListReq, opts ...grpc.CallOption) (*HomestayListResp, error)
		BusinessList(ctx context.Context, in *BusinessListReq, opts ...grpc.CallOption) (*BusinessListResp, error)
		GuessList(ctx context.Context, in *GuessListReq, opts ...grpc.CallOption) (*GuessListResp, error)
		HomestayDetail(ctx context.Context, in *HomestayDetailReq, opts ...grpc.CallOption) (*HomestayDetailResp, error)
		// 民宿商家服务
		GoodBoss(ctx context.Context, in *GoodBossReq, opts ...grpc.CallOption) (*GoodBossResp, error)
		HomestayBussinessList(ctx context.Context, in *HomestayBussinessListReq, opts ...grpc.CallOption) (*HomestayBussinessListResp, error)
		HomestayBussinessDetail(ctx context.Context, in *HomestayBussinessDetailReq, opts ...grpc.CallOption) (*HomestayBussinessDetailResp, error)
		// 民宿评论服务
		CommentList(ctx context.Context, in *CommentListReq, opts ...grpc.CallOption) (*CommentListResp, error)
	}

	defaultHomestayService struct {
		cli zrpc.Client
	}
)

func NewHomestayService(cli zrpc.Client) HomestayService {
	return &defaultHomestayService{
		cli: cli,
	}
}

// 民宿服务
func (m *defaultHomestayService) HomestayList(ctx context.Context, in *HomestayListReq, opts ...grpc.CallOption) (*HomestayListResp, error) {
	client := pb.NewHomestayServiceClient(m.cli.Conn())
	return client.HomestayList(ctx, in, opts...)
}

func (m *defaultHomestayService) BusinessList(ctx context.Context, in *BusinessListReq, opts ...grpc.CallOption) (*BusinessListResp, error) {
	client := pb.NewHomestayServiceClient(m.cli.Conn())
	return client.BusinessList(ctx, in, opts...)
}

func (m *defaultHomestayService) GuessList(ctx context.Context, in *GuessListReq, opts ...grpc.CallOption) (*GuessListResp, error) {
	client := pb.NewHomestayServiceClient(m.cli.Conn())
	return client.GuessList(ctx, in, opts...)
}

func (m *defaultHomestayService) HomestayDetail(ctx context.Context, in *HomestayDetailReq, opts ...grpc.CallOption) (*HomestayDetailResp, error) {
	client := pb.NewHomestayServiceClient(m.cli.Conn())
	return client.HomestayDetail(ctx, in, opts...)
}

// 民宿商家服务
func (m *defaultHomestayService) GoodBoss(ctx context.Context, in *GoodBossReq, opts ...grpc.CallOption) (*GoodBossResp, error) {
	client := pb.NewHomestayServiceClient(m.cli.Conn())
	return client.GoodBoss(ctx, in, opts...)
}

func (m *defaultHomestayService) HomestayBussinessList(ctx context.Context, in *HomestayBussinessListReq, opts ...grpc.CallOption) (*HomestayBussinessListResp, error) {
	client := pb.NewHomestayServiceClient(m.cli.Conn())
	return client.HomestayBussinessList(ctx, in, opts...)
}

func (m *defaultHomestayService) HomestayBussinessDetail(ctx context.Context, in *HomestayBussinessDetailReq, opts ...grpc.CallOption) (*HomestayBussinessDetailResp, error) {
	client := pb.NewHomestayServiceClient(m.cli.Conn())
	return client.HomestayBussinessDetail(ctx, in, opts...)
}

// 民宿评论服务
func (m *defaultHomestayService) CommentList(ctx context.Context, in *CommentListReq, opts ...grpc.CallOption) (*CommentListResp, error) {
	client := pb.NewHomestayServiceClient(m.cli.Conn())
	return client.CommentList(ctx, in, opts...)
}
