// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.5
// source: travel.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HomestayService_HomestayList_FullMethodName           = "/homestay.HomestayService/HomestayList"
	HomestayService_BusinessList_FullMethodName           = "/homestay.HomestayService/BusinessList"
	HomestayService_GuessList_FullMethodName              = "/homestay.HomestayService/GuessList"
	HomestayService_HomestayDetail_FullMethodName         = "/homestay.HomestayService/HomestayDetail"
	HomestayService_GoodBoss_FullMethodName               = "/homestay.HomestayService/GoodBoss"
	HomestayService_HomestayBusinessList_FullMethodName   = "/homestay.HomestayService/HomestayBusinessList"
	HomestayService_HomestayBusinessDetail_FullMethodName = "/homestay.HomestayService/HomestayBusinessDetail"
	HomestayService_CommentList_FullMethodName            = "/homestay.HomestayService/CommentList"
)

// HomestayServiceClient is the client API for HomestayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ========== 服务定义 ==========
type HomestayServiceClient interface {
	// 民宿服务
	HomestayList(ctx context.Context, in *HomestayListReq, opts ...grpc.CallOption) (*HomestayListResp, error)
	BusinessList(ctx context.Context, in *BusinessListReq, opts ...grpc.CallOption) (*BusinessListResp, error)
	GuessList(ctx context.Context, in *GuessListReq, opts ...grpc.CallOption) (*GuessListResp, error)
	HomestayDetail(ctx context.Context, in *HomestayDetailReq, opts ...grpc.CallOption) (*HomestayDetailResp, error)
	// 民宿商家服务
	GoodBoss(ctx context.Context, in *GoodBossReq, opts ...grpc.CallOption) (*GoodBossResp, error)
	HomestayBusinessList(ctx context.Context, in *HomestayBusinessListReq, opts ...grpc.CallOption) (*HomestayBusinessListResp, error)
	HomestayBusinessDetail(ctx context.Context, in *HomestayBusinessDetailReq, opts ...grpc.CallOption) (*HomestayBusinessDetailResp, error)
	// 民宿评论服务
	CommentList(ctx context.Context, in *CommentListReq, opts ...grpc.CallOption) (*CommentListResp, error)
}

type homestayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHomestayServiceClient(cc grpc.ClientConnInterface) HomestayServiceClient {
	return &homestayServiceClient{cc}
}

func (c *homestayServiceClient) HomestayList(ctx context.Context, in *HomestayListReq, opts ...grpc.CallOption) (*HomestayListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomestayListResp)
	err := c.cc.Invoke(ctx, HomestayService_HomestayList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homestayServiceClient) BusinessList(ctx context.Context, in *BusinessListReq, opts ...grpc.CallOption) (*BusinessListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BusinessListResp)
	err := c.cc.Invoke(ctx, HomestayService_BusinessList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homestayServiceClient) GuessList(ctx context.Context, in *GuessListReq, opts ...grpc.CallOption) (*GuessListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuessListResp)
	err := c.cc.Invoke(ctx, HomestayService_GuessList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homestayServiceClient) HomestayDetail(ctx context.Context, in *HomestayDetailReq, opts ...grpc.CallOption) (*HomestayDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomestayDetailResp)
	err := c.cc.Invoke(ctx, HomestayService_HomestayDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homestayServiceClient) GoodBoss(ctx context.Context, in *GoodBossReq, opts ...grpc.CallOption) (*GoodBossResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoodBossResp)
	err := c.cc.Invoke(ctx, HomestayService_GoodBoss_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homestayServiceClient) HomestayBusinessList(ctx context.Context, in *HomestayBusinessListReq, opts ...grpc.CallOption) (*HomestayBusinessListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomestayBusinessListResp)
	err := c.cc.Invoke(ctx, HomestayService_HomestayBusinessList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homestayServiceClient) HomestayBusinessDetail(ctx context.Context, in *HomestayBusinessDetailReq, opts ...grpc.CallOption) (*HomestayBusinessDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomestayBusinessDetailResp)
	err := c.cc.Invoke(ctx, HomestayService_HomestayBusinessDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *homestayServiceClient) CommentList(ctx context.Context, in *CommentListReq, opts ...grpc.CallOption) (*CommentListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentListResp)
	err := c.cc.Invoke(ctx, HomestayService_CommentList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HomestayServiceServer is the server API for HomestayService service.
// All implementations must embed UnimplementedHomestayServiceServer
// for forward compatibility.
//
// ========== 服务定义 ==========
type HomestayServiceServer interface {
	// 民宿服务
	HomestayList(context.Context, *HomestayListReq) (*HomestayListResp, error)
	BusinessList(context.Context, *BusinessListReq) (*BusinessListResp, error)
	GuessList(context.Context, *GuessListReq) (*GuessListResp, error)
	HomestayDetail(context.Context, *HomestayDetailReq) (*HomestayDetailResp, error)
	// 民宿商家服务
	GoodBoss(context.Context, *GoodBossReq) (*GoodBossResp, error)
	HomestayBusinessList(context.Context, *HomestayBusinessListReq) (*HomestayBusinessListResp, error)
	HomestayBusinessDetail(context.Context, *HomestayBusinessDetailReq) (*HomestayBusinessDetailResp, error)
	// 民宿评论服务
	CommentList(context.Context, *CommentListReq) (*CommentListResp, error)
	mustEmbedUnimplementedHomestayServiceServer()
}

// UnimplementedHomestayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHomestayServiceServer struct{}

func (UnimplementedHomestayServiceServer) HomestayList(context.Context, *HomestayListReq) (*HomestayListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomestayList not implemented")
}
func (UnimplementedHomestayServiceServer) BusinessList(context.Context, *BusinessListReq) (*BusinessListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BusinessList not implemented")
}
func (UnimplementedHomestayServiceServer) GuessList(context.Context, *GuessListReq) (*GuessListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GuessList not implemented")
}
func (UnimplementedHomestayServiceServer) HomestayDetail(context.Context, *HomestayDetailReq) (*HomestayDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomestayDetail not implemented")
}
func (UnimplementedHomestayServiceServer) GoodBoss(context.Context, *GoodBossReq) (*GoodBossResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoodBoss not implemented")
}
func (UnimplementedHomestayServiceServer) HomestayBusinessList(context.Context, *HomestayBusinessListReq) (*HomestayBusinessListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomestayBusinessList not implemented")
}
func (UnimplementedHomestayServiceServer) HomestayBusinessDetail(context.Context, *HomestayBusinessDetailReq) (*HomestayBusinessDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomestayBusinessDetail not implemented")
}
func (UnimplementedHomestayServiceServer) CommentList(context.Context, *CommentListReq) (*CommentListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentList not implemented")
}
func (UnimplementedHomestayServiceServer) mustEmbedUnimplementedHomestayServiceServer() {}
func (UnimplementedHomestayServiceServer) testEmbeddedByValue()                         {}

// UnsafeHomestayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HomestayServiceServer will
// result in compilation errors.
type UnsafeHomestayServiceServer interface {
	mustEmbedUnimplementedHomestayServiceServer()
}

func RegisterHomestayServiceServer(s grpc.ServiceRegistrar, srv HomestayServiceServer) {
	// If the following call pancis, it indicates UnimplementedHomestayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HomestayService_ServiceDesc, srv)
}

func _HomestayService_HomestayList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomestayListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomestayServiceServer).HomestayList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomestayService_HomestayList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomestayServiceServer).HomestayList(ctx, req.(*HomestayListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomestayService_BusinessList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BusinessListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomestayServiceServer).BusinessList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomestayService_BusinessList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomestayServiceServer).BusinessList(ctx, req.(*BusinessListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomestayService_GuessList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuessListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomestayServiceServer).GuessList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomestayService_GuessList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomestayServiceServer).GuessList(ctx, req.(*GuessListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomestayService_HomestayDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomestayDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomestayServiceServer).HomestayDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomestayService_HomestayDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomestayServiceServer).HomestayDetail(ctx, req.(*HomestayDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomestayService_GoodBoss_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodBossReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomestayServiceServer).GoodBoss(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomestayService_GoodBoss_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomestayServiceServer).GoodBoss(ctx, req.(*GoodBossReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomestayService_HomestayBusinessList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomestayBusinessListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomestayServiceServer).HomestayBusinessList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomestayService_HomestayBusinessList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomestayServiceServer).HomestayBusinessList(ctx, req.(*HomestayBusinessListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomestayService_HomestayBusinessDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomestayBusinessDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomestayServiceServer).HomestayBusinessDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomestayService_HomestayBusinessDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomestayServiceServer).HomestayBusinessDetail(ctx, req.(*HomestayBusinessDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HomestayService_CommentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HomestayServiceServer).CommentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HomestayService_CommentList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HomestayServiceServer).CommentList(ctx, req.(*CommentListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// HomestayService_ServiceDesc is the grpc.ServiceDesc for HomestayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HomestayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "homestay.HomestayService",
	HandlerType: (*HomestayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HomestayList",
			Handler:    _HomestayService_HomestayList_Handler,
		},
		{
			MethodName: "BusinessList",
			Handler:    _HomestayService_BusinessList_Handler,
		},
		{
			MethodName: "GuessList",
			Handler:    _HomestayService_GuessList_Handler,
		},
		{
			MethodName: "HomestayDetail",
			Handler:    _HomestayService_HomestayDetail_Handler,
		},
		{
			MethodName: "GoodBoss",
			Handler:    _HomestayService_GoodBoss_Handler,
		},
		{
			MethodName: "HomestayBusinessList",
			Handler:    _HomestayService_HomestayBusinessList_Handler,
		},
		{
			MethodName: "HomestayBusinessDetail",
			Handler:    _HomestayService_HomestayBusinessDetail_Handler,
		},
		{
			MethodName: "CommentList",
			Handler:    _HomestayService_CommentList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "travel.proto",
}
