// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: travel.proto

package server

import (
	"context"

	"go-zero-looklook/app/travel/rpc/pb"
	"go-zero-looklook/app/travel/rpc/internal/logic"
	"go-zero-looklook/app/travel/rpc/internal/svc"
)

type HomestayServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedHomestayServiceServer
}

func NewHomestayServiceServer(svcCtx *svc.ServiceContext) *HomestayServiceServer {
	return &HomestayServiceServer{
		svcCtx: svcCtx,
	}
}

// 民宿服务
func (s *HomestayServiceServer) HomestayList(ctx context.Context, in *pb.HomestayListReq) (*pb.HomestayListResp, error) {
	l := logic.NewHomestayListLogic(ctx, s.svcCtx)
	return l.HomestayList(in)
}

func (s *HomestayServiceServer) BusinessList(ctx context.Context, in *pb.BusinessListReq) (*pb.BusinessListResp, error) {
	l := logic.NewBusinessListLogic(ctx, s.svcCtx)
	return l.BusinessList(in)
}

func (s *HomestayServiceServer) GuessList(ctx context.Context, in *pb.GuessListReq) (*pb.GuessListResp, error) {
	l := logic.NewGuessListLogic(ctx, s.svcCtx)
	return l.GuessList(in)
}

func (s *HomestayServiceServer) HomestayDetail(ctx context.Context, in *pb.HomestayDetailReq) (*pb.HomestayDetailResp, error) {
	l := logic.NewHomestayDetailLogic(ctx, s.svcCtx)
	return l.HomestayDetail(in)
}

// 民宿商家服务
func (s *HomestayServiceServer) GoodBoss(ctx context.Context, in *pb.GoodBossReq) (*pb.GoodBossResp, error) {
	l := logic.NewGoodBossLogic(ctx, s.svcCtx)
	return l.GoodBoss(in)
}

func (s *HomestayServiceServer) HomestayBusinessList(ctx context.Context, in *pb.HomestayBusinessListReq) (*pb.HomestayBusinessListResp, error) {
	l := logic.NewHomestayBusinessListLogic(ctx, s.svcCtx)
	return l.HomestayBusinessList(in)
}

func (s *HomestayServiceServer) HomestayBusinessDetail(ctx context.Context, in *pb.HomestayBusinessDetailReq) (*pb.HomestayBusinessDetailResp, error) {
	l := logic.NewHomestayBusinessDetailLogic(ctx, s.svcCtx)
	return l.HomestayBusinessDetail(in)
}

// 民宿评论服务
func (s *HomestayServiceServer) CommentList(ctx context.Context, in *pb.CommentListReq) (*pb.CommentListResp, error) {
	l := logic.NewCommentListLogic(ctx, s.svcCtx)
	return l.CommentList(in)
}
