// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	homestay "go-zero-looklook/app/travel/api/internal/handler/homestay"
	homestayBusiness "go-zero-looklook/app/travel/api/internal/handler/homestayBusiness"
	homestayComment "go-zero-looklook/app/travel/api/internal/handler/homestayComment"
	"go-zero-looklook/app/travel/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// boss all homestay room
				Method:  http.MethodPost,
				Path:    "/homestay/businessList",
				Handler: homestay.BusinessListHandler(serverCtx),
			},
			{
				// guess homestay room
				Method:  http.MethodPost,
				Path:    "/homestay/guessList",
				Handler: homestay.GuessListHandler(serverCtx),
			},
			{
				// homestay room detail
				Method:  http.MethodPost,
				Path:    "/homestay/homestayDetail",
				Handler: homestay.HomestayDetailHandler(serverCtx),
			},
			{
				// homestay room list
				Method:  http.MethodPost,
				Path:    "/homestay/homestayList",
				Handler: homestay.HomestayListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/travel/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// good boss
				Method:  http.MethodPost,
				Path:    "/homestayBusiness/goodBoss",
				Handler: homestayBusiness.GoodBossHandler(serverCtx),
			},
			{
				// boss detail
				Method:  http.MethodPost,
				Path:    "/homestayBusiness/homestayBusinessDetail",
				Handler: homestayBusiness.HomestayBusinessDetailHandler(serverCtx),
			},
			{
				// business list
				Method:  http.MethodPost,
				Path:    "/homestayBusiness/homestayBusinessList",
				Handler: homestayBusiness.HomestayBusinessListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/travel/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// homestay comment list
				Method:  http.MethodPost,
				Path:    "/homestayComment/commentList",
				Handler: homestayComment.CommentListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/travel/v1"),
	)
}
